name: usdtz-site
services:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
    build_command: "npm install && npm run build"
    run_command: "npm run preview"
    environment_slug: node-js
    http_port: 4173
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_ENV
        value: production
    output_dir: dist
